name: Issue Comment Workflow
on:
  issue_comment:
    types: [created]

jobs:
  print_message:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Mensaje
        run: echo "Comentario en PR detectado"
